CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    age INTEGER NOT NULL,
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    role VARCHAR(20) NOT NULL,
    banned BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE tariffs (
    tariff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_type VARCHAR(50) NOT NULL,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    discount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE rental_points (
    rental_point_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    parent_point_id BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_rental_points_rental_points
    FOREIGN KEY (parent_point_id)
    REFERENCES rental_points(rental_point_id)
);

CREATE TABLE scooters (
    scooter_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    battery_level INTEGER NOT NULL DEFAULT 100,
    scooter_status VARCHAR(50) NOT NULL DEFAULT 'IN_WAREHOUSE',
    rental_point_id BIGINT DEFAULT NULL,

    CONSTRAINT fk_scooters_rental_point
    FOREIGN KEY (rental_point_id)
    REFERENCES rental_points(rental_point_id)
);

CREATE TABLE trips (
    trip_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scooter_id BIGINT NOT NULL,
    trip_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    start_point_id BIGINT NOT NULL,
    end_point_id BIGINT,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    total_cost DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    tariff_id BIGINT NOT NULL,

    CONSTRAINT fk_trips_users
    FOREIGN KEY (user_id)
    REFERENCES users(user_id),

    CONSTRAINT fk_trips_scooters
    FOREIGN KEY (scooter_id)
    REFERENCES scooters(scooter_id),

    CONSTRAINT fk_trips_start_point
    FOREIGN KEY (start_point_id)
    REFERENCES rental_points(rental_point_id),

    CONSTRAINT fk_trips_end_point
    FOREIGN KEY (end_point_id)
    REFERENCES rental_points(rental_point_id),

    CONSTRAINT fk_trips_tariffs
    FOREIGN KEY (tariff_id)
    REFERENCES tariffs(tariff_id)
);
